### PR TITLE
Ks 039 nov 05 logout error 2537

### LINKED ISSUE #2537: Console error upon logout
```
index-DzsA5Ui5.js:891 Error getting all users: CustomException: Bad Request
    at VA (index-DzsA5Ui5.js:299:44961)
    at Object.get (index-DzsA5Ui5.js:299:45573)
    at async Ns (index-DzsA5Ui5.js:891:33896)
    at async index-DzsA5Ui5.js:1109:78255
index-DzsA5Ui5.js:1109 Error checking if user exists: CustomException: Bad Request
    at VA (index-DzsA5Ui5.js:299:44961)
    at Object.get (index-DzsA5Ui5.js:299:45573)
    at async Ns (index-DzsA5Ui5.js:891:33896)
    at async index-DzsA5Ui5.js:1109:78255
﻿
```

### PR DESCRIPTION
**Pull request by solan117**
## Describe your changes

- add caching to reduce redundant API calls
- remove unused optional authToken parameter from methods
- prevent unnecessary API calls and handle invalid token early

## Write your issue number after "Fixes "

Fixes #2537  

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I have avoided using hardcoded values to ensure scalability and maintain consistency across the application.
- [x] I have ensured that font sizes, color choices, and other UI elements are referenced from the theme.
- [x] My pull request is focused and addresses a single, specific feature.
- [ ] If there are UI changes, I have attached a screenshot or video to this PR.

### CODE REVIEW

File: Clients/src/presentation/components/ProtectedRoute/index.tsx [hunk 1]
```diff
@@ -67,8 +68,17 @@ const ProtectedRoute = ({ Component, ...rest }: IProtectedRouteProps) => {
         setLoading(false);
       }
     };
-    checkUserExistsInDatabase();
-  }, [dispatch, authState.authToken]);
+
+    // Only run the check if we're not on public auth pages and we have a valid token
+    // This prevents unnecessary API calls during logout
+    const shouldRunCheck = !isPublicRoute && authState.authToken && authState.authToken.trim() !== "";
```
Comment (Br0wnHammer) [inline Clients/src/presentation/components/ProtectedRoute/index.tsx]: Why create a variable if you are only going to use it once. Just use the condition directly.

Comment (Br0wnHammer) [inline Clients/src/presentation/components/ProtectedRoute/index.tsx]: The .trim() !== "" check is redundant since authState.authToken is already truthy which filters empty strings.

File: Clients/src/application/hooks/useIsMultiTenant.ts [hunk 2]
```diff
@@ -1,22 +1,63 @@
...
-          window.location.hostname === "test.verifywise.ai"
-        )
+        organizationCheckCache &&
+        organizationCheckCache.exists !== null &&
+        now - organizationCheckCache.timestamp < CACHE_DURATION
       ) {
+        // Use cached value
+        if (
+          !organizationCheckCache.exists || (
+            window.location.host === "app.verifywise.ai" ||
```
Comment (Br0wnHammer) [inline Clients/src/application/hooks/useIsMultiTenant.ts]: Why are you using .host for one and .hostname for the other? `.host` includes the port, `.hostname` doesn't.

File: Clients/src/application/hooks/useIsMultiTenant.ts [hunk 3]
```diff
@@ -1,22 +1,63 @@
...
+        if (
+          !exists || (
+            window.location.host === "app.verifywise.ai" ||
+            window.location.hostname === "test.verifywise.ai"
+          )
+        ) {
+          setIsMultiTenant(true);
+        }
+      } catch (error) {
+        console.error("Error checking organization existence:", error);
```
Comment (Br0wnHammer) [inline Clients/src/application/hooks/useIsMultiTenant.ts]: Best not to console log on the client side. We should refrain from using console errors on the client.

**Review by Br0wnHammer — CHANGES_REQUESTED** [review]
@solan117 Please see my comments. Some changes are needed.

File: Clients/src/application/hooks/useIsMultiTenant.ts (hunk 3 above)
Comment (solan117) [reply Clients/src/application/hooks/useIsMultiTenant.ts]: I used console.error() to debug log API failures then forgot to remove it. Thanks for pointing out.

File: Clients/src/application/hooks/useIsMultiTenant.ts [hunk 4]
```diff
@@ -1,22 +1,63 @@
...
+        const response = await CustomAxios.get("/organizations/exists");
+        const exists = response.data.data.exists;
+
+        // Update cache
+        organizationCheckCache = {
+          exists,
+          timestamp: now
+        };
+
+        if (
```
Comment (Br0wnHammer) [inline Clients/src/application/hooks/useIsMultiTenant.ts]: The duplicate `setIsMultiTenant`(true) logic is redundant. We can simply alter the logic to take care of it once.

File: Clients/src/application/hooks/useIsMultiTenant.ts [hunk 5]
```diff
@@ -1,22 +1,63 @@
...
+          !exists || (
+            window.location.hostname === "app.verifywise.ai" ||
+            window.location.hostname === "test.verifywise.ai"
+          )
+        ) {
+          setIsMultiTenant(true);
+        }
+      } catch (error) {
```
Comment (Br0wnHammer) [inline Clients/src/application/hooks/useIsMultiTenant.ts:54]: Even though error is handled at server. Best practice would be to take care of it on the FE too.

**Comment by MuhammadKhalilzadeh** [comment]
@rachanabasnet Would you please do a review here, as well?

**Review by Br0wnHammer — APPROVED** [review]
LGTM!
