### PR TITLE
fix: Update risk data after a vendor is deleted

### LINKED ISSUE #1127: **Vendor Deletion & Related Updates**
- [x] Confirm that deleting a vendor appropriately updates related risk records (e.g., setting the vendor field to null or a default value).
- [ ] Verify that risk records remain editable and clickable after vendor deletion.

### PR DESCRIPTION
**Pull request by srwa-rsp**
## Describe your changes

Refetch vendor risks upon vendor deletion

## Write your issue number after "Fixes "

Fixes  #1127

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

https://github.com/user-attachments/assets/49eeeb60-7726-4fd6-b703-59893e0c827f

## Summary by CodeRabbit

- **Bug Fixes**
  - Ensured the risks list is refreshed automatically after deleting a vendor.
- **Refactor**
  - Centralized vendor risk data fetching and state management into a dedicated hook.
  - Updated risk table to receive vendor risks data directly via props.
  - Improved loading state handling and re-fetch capabilities for vendor risks.

### CODE REVIEW

File: Clients/src/presentation/pages/Vendors/index.tsx [hunk 1]
```diff
@@ -217,6 +217,7 @@ const Vendors = () => {
           setAlert(null);
         }, 3000);
         await fetchVendors();
+        await  fetchRisks();
```
Comment (samuel-coutinho) [inline Clients/src/presentation/pages/Vendors/index.tsx:220]: I believe this is a good opportunity to improve the component. The `useVendorRisks` hook, which is currently being utilized here(line 78) to provide `vendorRisksSummary`, can fetch and provide all the necessary data. Therefore, we can eliminate the `fetchRisks` function located on line 152.

Additionally, we could modify this hook. Instead of using a state variable (refreshKey) to control when the API is called, we could follow the approach I described in our meeting: create a `fetchVendorsRisks` function within the hook, call it inside a `useEffect` that runs only once, and expose the function as `refetchVendorRisks`. This way, we can call `refetchVendorRisks` in the component whenever it's needed.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]
Thank you, @srwa-rsp. I have a suggestion to improve the fetch logic a bit.

File: Clients/src/presentation/pages/Vendors/index.tsx (hunk 1 above)
Comment (srwa-rsp) [reply Clients/src/presentation/pages/Vendors/index.tsx]: Thanks for your feedback @samuel-coutinho ! I've made the changes as you suggested. Let me know if there’s anything else you’d like me to adjust.

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Thank you @srwa-rsp 
It's working as explained
Kudos ✅

**Review by MuhammadKhalilzadeh — APPROVED** [review]
