### PR TITLE
Fix/broken loading states in reporting module

### LINKED ISSUE #3546: Fix broken loading states in Reporting module
## Problem

Multiple pages use raw text strings or unstyled `<div>` elements as `<Suspense>` fallbacks instead of the `<CustomizableSkeleton>` component used elsewhere in the platform.

### All locations (7 instances across 4 files)

**`Reporting/index.tsx` (line 24):**
\`\`\`tsx
<Suspense fallback={"loading..."}>
  <ReportLists ... />
</Suspense>
\`\`\`

**`Reporting/GenerateReport/index.tsx` (lines 195, 201):**
\`\`\`tsx
<Suspense fallback={"loading..."}>
  <ReportStatus isDisabled={isDisabled} />
</Suspense>

<Suspense fallback={"loading..."}>
  <GenerateReportPopup ... />
</Suspense>
\`\`\`

**`components/Reporting/GenerateReport/index.tsx` (lines 397, 421, 428, 438):**
\`\`\`tsx
<Suspense fallback={<div>Loading...</div>}>
  ...
</Suspense>
\`\`\`
(4 instances)

**`Vendors/index.tsx` (line 1089):**
\`\`\`tsx
<Suspense fallback={<div>Loading...</div>}>
\`\`\`

## Impact

Users see plain unstyled text flash on screen while components load, breaking the polished skeleton loading pattern used across the rest of the platform.

## Solution

Replace all raw text/div fallbacks with `<CustomizableSkeleton>` (`components/Skeletons/index.tsx`). This component already exists and is used for conditional loading states elsewhere — it just hasn't been applied to Suspense fallbacks yet.

7 instances across 4 files.

### PR DESCRIPTION
**Pull request by Innagl**
## Describe your changes

Removed premature skeleton above the filter bar caused by the outer <Suspense> in Reporting/index.tsx

## Write your issue number after "Fixes "

Fixes #3546 

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I have avoided using hardcoded values to ensure scalability and maintain consistency across the application.
- [ ] I have ensured that font sizes, color choices, and other UI elements are referenced from the theme.
- [x] My pull request is focused and addresses a single, specific feature.
- [x] If there are UI changes, I have attached a screenshot or video to this PR.

https://github.com/user-attachments/assets/1a3ac230-bb5d-4e5e-965b-9a60fbf8843e

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
LGTM!

File: Clients/src/presentation/pages/Reporting/Reports/index.tsx [hunk 1]
```diff
@@ -382,7 +382,7 @@ const Reports: React.FC<ReportsProps> = ({
       }}
     >
       {alert && (
-        <Suspense fallback={<div>Loading...</div>}>
+        <Suspense fallback={null}>
```
Comment (Br0wnHammer) [inline Clients/src/presentation/pages/Reporting/Reports/index.tsx]: Best would be to remove the suspense wrap around the alert. This wrapper does nothing because it only catches lazy/async boundaries. and adds noise.

**Review by Br0wnHammer — CHANGES_REQUESTED** [review]
Solid work as always. Just a minor change needed 👍🏼

**Review by Br0wnHammer — APPROVED** [review]
LGTM!
