### PR TITLE
Fix: Project Framework ID from FE to BE

### LINKED ISSUE #1530: Project Framework Id in Report Module
as discussed, we require project framework id from FE to BE for proper fetching of data in the ISO-42001 framework.

### PR DESCRIPTION
**Pull request by Br0wnHammer**
## Describe your changes

This PR address the implementation of `projectFrameworkId `and the seperation of `framework_id` and `project_framework_id`.

## Write your issue number after "Fixes "

Fixes #1530 

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I have avoided using hardcoded values to ensure scalability and maintain consistency across the application.
- [x] My pull request is focused and addresses a single, specific feature.

## Summary by CodeRabbit

- **New Features**
  - Added support for specifying both framework and project framework when generating reports, allowing for more precise report customization.

- **Bug Fixes**
  - Improved consistency in naming conventions for framework identifiers across the report generation workflow.

- **Refactor**
  - Streamlined how framework and project framework IDs are handled throughout the report generation process for better maintainability.

### CODE REVIEW

File: Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx [hunk 1]
```diff
@@ -23,20 +23,23 @@ interface FormValues {
   report_name: string;
   project: number;
   framework: number;
+  project_framework_id: number;
```
Comment (samuel-coutinho) [inline Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx]: Please use camel case for JavaScript in the front end to maintain consistency.

File: Servers/services/markdowns/annexesMarkdown.ts [hunk 2]
```diff
@@ -43,12 +44,13 @@ ${clausesAndAnnexesReportData}
...
 
 export async function getClausesAndAnnexesReportData (
+  frameworkId: number,
   projectFrameworkId: number
 ) : Promise<string> {
   let annexRows: string = ``;
   let clausesReportData: string = ``;
   try {
-    const annexesReportData = await getAnnexesReportQuery(projectFrameworkId) as AllAnnexes[];    
+    const annexesReportData = await getAnnexesReportQuery(frameworkId) as AllAnnexes[];
```
[the remark this answers is not in the document]
Comment (samuel-coutinho) [reply Servers/services/markdowns/annexesMarkdown.ts]: I recommend accepting this comment.

File: Servers/controllers/reporting.ctrl.ts [hunk 3]
```diff
@@ -61,7 +61,8 @@ export async function generateReports(
       projectTitle,
       projectOwner,
       frameworkId: frameworkIdRaw,
-      reportName
+      reportName,
+      projectFrameworkId
     } = req.body;
```
[the remark this answers is not in the document]
Comment (samuel-coutinho) [reply Servers/controllers/reporting.ctrl.ts:66]: We have a validation for ids in the requests:
`router.post("/generate-report", authenticateJWT, validateId("projectId"), validateId("frameworkId"), generateReports);`
Please @Br0wnHammer, add a validation for `projectFrameworkId` as well.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]
I have a couple of comments.

File: Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx [hunk 4]
```diff
@@ -95,6 +98,21 @@ const GenerateReportFrom: React.FC<ReportProps> = ({ onGenerate }) => {
     [values, errors]
   );
 
+  const handleFrameworkChange = (event: SelectChangeEvent<string | number>) => {
```
Comment (MuhammadKhalilzadeh) [inline Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx]: Thank you for the great implementation. Just a few tiny suggestions, now that we are almost there with the release:

The handler uses `SelectChangeEvent<string | number>`, but you cast to `Number` anyway. It may be clearer to use just `SelectChangeEvent<number>` if possible, or handle the conversion in a utility function for better safety and readability.

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Thank you @Br0wnHammer for the implementation.

**Comment by MuhammadKhalilzadeh** [comment]
Let's wait for others' review as well, then we go for the merge

File: Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx (hunk 4 above)
Comment (samuel-coutinho) [reply Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx]: Upon examining this component more closely, I believe we do not need a new handler. The previous implementation using `onChange={handleOnSelectChange("framework")}` is appropriate. What we really need is to update the `projectFramework`, which depends on both the selected project and the framework. Currently, there is a `useEffect` on line 81 that handles this update when `values.project` changes.

To improve efficiency and avoid unnecessary re-renders, I propose replacing the `useEffect` with the following code:

```javascript
const projectFrameworks = useMemo<FrameworkValues[]>(() => {
    const selectedProject = dashboardValues.projects.find(
        (project: { id: string | number }) => project.id === values.project
    );

    const frameworks = selectedProject?.framework;

    return Array.isArray(frameworks) && frameworks.length > 0
        ? frameworks
        : [initialFrameworkValue];
}, [dashboardValues.projects, values.project]);

const projectFrameworkId = useMemo(() => {
    return projectFrameworks.find(
        (pf) => pf.framework_id === values.framework
    )?.project_framework_id ?? 1;
}, [projectFrameworks, values.framework]);
```

Then, in the `handleFormSubmit` function, we can modify it as follows:

```javascript
const handleFormSubmit = () => {
    const newValues = {
        ...values,
        projectFrameworkId: projectFrameworkId,
    };
    onGenerate(newValues);
};
```

Additionally, we can eliminate the line:

```javascript
const [projectFrameworks, setProjectFrameworks] = useState<FrameworkValues[]>([initialFrameworkValue]);
```

What are your thoughts on this approach?

Comment (Br0wnHammer) [reply Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx]: @samuel-coutinho I believe your suggested approach will be more effective because each time a different framework is chosen for a project, the component undergoes multiple re-renders, leading to performance overhead.

@MuhammadKhalilzadeh what say?

Comment (MuhammadKhalilzadeh) [reply Clients/src/presentation/components/Reporting/GenerateReport/GenerateReportFrom/index.tsx]: > @samuel-coutinho I believe your suggested approach will be more effective because each time a different framework is chosen for a project, the component undergoes multiple re-renders, leading to performance overhead.
> 
> @MuhammadKhalilzadeh what say?

I agree
Thank you @samuel-coutinho and @Br0wnHammer you both.
Let's apply changes

**Comment by MuhammadKhalilzadeh** [comment]
@HarshP4585 Would please do a quick review here as well?

File: Servers/services/reportService.ts [hunk 5]
```diff
@@ -98,13 +99,13 @@ export async function getReportData(
       markdownFormattedData = await getVendorReportMarkdown(projectId, reportBody)
       break;
     case ReportType.ANNEXES_REPORT:
-      markdownFormattedData = await getClausesAndAnnexesMarkdown(frameworkId, reportBody)
+      markdownFormattedData = await getClausesAndAnnexesMarkdown(frameworkId, projectFrameworkId, reportBody)
```
Comment (HarshP4585) [inline Servers/services/reportService.ts]: Here we can remove `frameworkId`, as in the `getClausesAndAnnexesMarkdown` definition we are expecting `projectFrameworkId` and the frameworkId is not used the function

**Review by HarshP4585 — CHANGES_REQUESTED** [review]
Just a small change

**Comment by Br0wnHammer** [comment]
> Just a small change

Have implemented the said changes. 👍🏼

**Review by samuel-coutinho — APPROVED** [review]

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Thank you so much @Br0wnHammer for the implementation
