### PR TITLE
Fix file upload issue

### LINKED ISSUE #1306: File Upload/Delete not working on Compliance and Assestment
Image

### PR DESCRIPTION
**Pull request by HarshP4585**
## Describe your changes

- Fix file upload issue
   image
   image

## Write your issue number after "Fixes "

Fixes #1306 

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved stability when accessing project framework IDs in project cards and various views by safely handling cases where data may be missing.
- **Refactor**
	- Updated terminology throughout the app, renaming identifiers such as `id` to `question_id` and `project_framework_id` to `project_id` for consistency.
	- Simplified file upload endpoints and internal references for improved maintainability.
- **New Features**
	- Adjusted file upload routes to use updated API paths.
- **Enhancements**
	- Added informational alerts prompting users to save changes after file uploads or deletions.
	- Removed success alert on file deletion to streamline user notifications.

### CODE REVIEW

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]
Looks great @HarshP4585. There is just one small problem. The confirmation toast when a file is deleted in the compliance tracker is positioned inside the modal, when it should be in the top right corner of the screen. Could you please fix this? You can delete a file on the Assessment tracker page to see what it should look like.

**Comment by HarshP4585** [comment]
@samuel-coutinho Added info log, to save the changes in-order to save the file changes

image

File: Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx [hunk 1]
```diff
@@ -101,11 +101,11 @@ const AuditorFeedback: React.FC<AuditorFeedbackProps> = ({
...
-    handleAlert({
-      variant: "success",
-      body: "File deleted successfully",
-      setAlert,
-    });
+    // handleAlert({
+    //   variant: "success",
+    //   body: "File deleted successfully",
+    //   setAlert,
+    // });
```
Comment (samuel-coutinho) [inline Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx:108]: Please remove this commented code.

File: Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx [hunk 2]
```diff
@@ -192,6 +193,15 @@ const NewControlPane = ({
...
     }));
+    if (deletedFilesIds.length > 0 || files.length > 0) {
+      setAlert({
+        type: "info",
+        message: `Please save the changes to save the file changes.`,
+      })
+      setTimeout(() => {
+        setAlert(null);
+      }, 1000);
+    }
```
Comment (samuel-coutinho) [inline Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx:204]: I think the type of message should be a warning here. And it should appear if the user tries to close the modal or switch between tabs with a pending file. Could you confirm the behaviour here, Gorkem? This screenshot shows the toast.
https://github.com/bluewave-labs/verifywise/pull/1371#issuecomment-2885492729

Additionally, please use the function `handleAlert` to trigger the toast. It already contains the logic to close it with a standard timeout.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]
In fact, what we need when deleting the file is to show a confirmation or error, like here:
Screenshot_20250516_100128

**Comment by HarshP4585** [comment]
I guess in the assessment tracker, we are deleting file via file route. But, in the compliance tracker we are deleting and uploading the file via the /saveControls route. So, I added an info log which will let the user know to save the controls to save the file changes

File: Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx (hunk 1 above)
Comment (HarshP4585) [reply Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx]: Removed

**Review by samuel-coutinho — APPROVED** [review]
Thanks, Harsh. I will talk to Gorkem about how to proceed with deleting a file, and if necessary, we will change it in the future.
