### PR TITLE
Fix "Generate report" disable

### LINKED ISSUE #1495: Fix GenerateReport isDisabled condition
Currently, the `GenerateReport` component disables the "Generate your report" button based on the existence of `selectedProjectId`. However, at this stage of the app, we do not have this value since it will be selected later.

```javascript
const { selectedProjectId } = dashboardValues;
const isDisabled = selectedProjectId ? false : true;
```

Instead, we should disable the button based on whether the length of the `projects` array is equal to 0.

Rather than using context to extract the projects, it would be more effective to call the `Clients/src/application/hooks/useFetchProjects.ts` hook to obtain the projects object.

Additionally, we should consider renaming the hook to `useProjects` to better reflect its purpose.

### PR DESCRIPTION
**Pull request by HarshP4585**
## Describe your changes

- Fix the "Generate report" to be disable if the length of project is more than 0
- Updated the project delete to update the projects in context
- Renamed the `useFetchProjects` to `useProjects`

https://github.com/user-attachments/assets/0d9effb9-82c6-4ae4-849c-fcc5a00890b5

## Write your issue number after "Fixes "

Fixes #1495

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I have avoided using hardcoded values to ensure scalability and maintain consistency across the application.
- [ ] I have ensured that font sizes, color choices, and other UI elements are referenced from the theme.
- [ ] My pull request is focused and addresses a single, specific feature.
- [ ] If there are UI changes, I have attached a screenshot or video to this PR.

## Summary by CodeRabbit

- **Refactor**
  - Renamed the project data hook for consistency across the application.
  - Updated all relevant components to use the new hook name for fetching project data.
  - Adjusted state initialization in report generation to assume project data is always present.
  - Improved project deletion handling to update the project list in real time after a project is removed.
  - Simplified logic for enabling the "Generate your report" button based on project availability.

### CODE REVIEW

File: Clients/src/presentation/pages/FileManager/index.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ import FileSteps from "./FileSteps";
 import VWSkeleton from "../../vw-v2-components/Skeletons";
 import { vwhomeHeading } from "../Home/1.0Home/style";
 import { useUserFilesMetaData } from "../../../application/hooks/useUserFilesMetaData";
-import { useProjectData } from "../../../application/hooks/useFetchProjects";
+import { useProjectData } from "../../../application/hooks/useProjects";
```
Comment (samuel-coutinho) [inline Clients/src/presentation/pages/FileManager/index.tsx:14]: We can rename the hook to `useProjects` as well to have the same name as the file.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]

**Comment by MuhammadKhalilzadeh** [comment]
@HarshP4585 You've got conflicts here
Please give me a heads up once you're done resolving

File: Clients/src/presentation/pages/FileManager/index.tsx (hunk 1 above)
Comment (HarshP4585) [reply Clients/src/presentation/pages/FileManager/index.tsx]: Renamed the hook

**Comment by HarshP4585** [comment]
@MuhammadKhalilzadeh resolved the conflicts
