### PR TITLE
Fix undefined subcontrols

### LINKED ISSUE #1320: Undefined Subcontrols
Image

### PR DESCRIPTION
**Pull request by HarshP4585**
## Describe your changes

- Fix undefined sub-controls due to API changes
image

## Write your issue number after "Fixes "

Fixes #1320 

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

## Summary by CodeRabbit

- **New Features**
  - Controls in the Compliance Tracker now display detailed subcontrol information, including counts of total and completed subcontrols.

- **Bug Fixes**
  - Progress metrics in project assessment and compliance responses are now consistently returned as integers.

- **Refactor**
  - Improved the way control data is managed and displayed in modals for a more streamlined user experience.
  - Enhanced update functions to avoid unnecessary database queries when no changes are provided.

### CODE REVIEW

**Comment by charurajput16** [comment]
@HarshP4585 - Thank you Harsh! This is working now.

File: Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx [hunk 1]
```diff
@@ -127,7 +127,14 @@ const ControlsTable: React.FC<ControlsTableProps> = ({
...
         });
-        setControls(response);
+        let _response = []
+        for (let control of response) {
+          const subControlsResponse = await getEntityById({
+            routeUrl: `eu-ai-act/controlById?controlId=${control.id}&projectFrameworkId=${projectFrameworkId}`,
+          });
+          _response.push({...subControlsResponse.data, ...control});
+        }
+        setControls(_response);
```
Comment (samuel-coutinho) [inline Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx:137]: We have a few issues to address here. First, we are making multiple asynchronous requests inside a for loop, which results in sequential execution. This means that the next fetch will not start until the previous one has completed, significantly slowing down performance.

To improve this, we should create a specific endpoint that retrieves all the data from the controls and subcontrols in a single call.

Additionally, it would be beneficial to move the logic for calling the API to a dedicated hook, which we can name `useControls`.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]

File: Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx (hunk 1 above)
Comment (HarshP4585) [reply Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx]: @samuel-coutinho Updated the route to get the controls by control category id and changes the UI code to only fetch the subControls if the modal is open.

File: Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx [hunk 2]
```diff
@@ -125,16 +130,9 @@ const ControlsTable: React.FC<ControlsTableProps> = ({
       setLoading(true);
       try {
         const response = await getEntityById({
-          routeUrl: `/eu-ai-act/controls/byControlCategoryId/${controlCategoryId}`,
+          routeUrl: `/eu-ai-act/controls/byControlCategoryId/${controlCategoryId}?projectFrameworkId=${projectFrameworkId}`,
```
Comment (samuel-coutinho) [inline Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx:133]: Good work. Now we could move the logic inside this useEffect to its hook, useControls, and call it here to obtain `controls`.

**Review by samuel-coutinho — CHANGES_REQUESTED** [review]
We are still making multiple calls to get the data, which is not efficient. But we will address this problem in the future. 
Additionally, there seems to be a bug with the completion bar, as it does not update every time. Could you please check this? 
image

**Comment by HarshP4585** [comment]
> We are still making multiple calls to get the data, which is not efficient. But we will address this problem in the future. Additionally, there seems to be a bug with the completion bar, as it does not update every time. Could you please check this? image

https://github.com/user-attachments/assets/653c6dfe-622f-4c5b-8363-f5dbde544f37

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Thank you @HarshP4585 
Worked fine for me on test
